# Generated by Django 3.0.6 on 2020-07-31 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='valor')),
                ('mail', models.EmailField(max_length=254, verbose_name='mail')),
                ('notified', models.BooleanField(default=False, verbose_name='notificado')),
            ],
            options={
                'verbose_name': 'petición',
                'verbose_name_plural': 'peticiones',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='nombre del tipo de dólar')),
            ],
            options={
                'verbose_name': 'tipo de dólar',
                'verbose_name_plural': 'tipos de dólar',
            },
        ),
        migrations.CreateModel(
            name='Dollar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='precio de compra')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='precio de venta')),
                ('issue_date', models.DateTimeField(verbose_name='fecha y hora')),
                ('origin', models.CharField(max_length=200, verbose_name='origen del precio')),
                ('dollar_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webscrapping.Type', verbose_name='tipo de dolar')),
            ],
            options={
                'verbose_name': 'dólar',
                'verbose_name_plural': 'dólares',
                'ordering': ['issue_date'],
                'unique_together': {('issue_date', 'origin')},
            },
        ),
    ]
