# Generated by Django 3.0.6 on 2020-06-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolarscrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dollar',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dollar',
            name='issue_date',
            field=models.DateTimeField(default='2012-09-04 06:00:00.000000-08:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dollar',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
            preserve_default=False,
        ),
    ]
