# Generated by Django 3.0.6 on 2020-06-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolarscrap', '0003_auto_20200601_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollar',
            name='issue_date',
            field=models.DateTimeField(default='2012-09-04 06:00:00.000000-08:00'),
            preserve_default=False,
        ),
    ]
